version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html

  mysql: 
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: test
      MYSQL_USER: john
      MYSQL_PASSWORD: secret

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306